<a href="https://colab.research.google.com/github/johannesR17/predicciones-de-ventas/blob/main/Bakery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **CODING DOJO: Introducción a NumPy**
## Creado por: Johannes Rodríguez

* Fecha creado: 19/02/2023
* Fecha de actualización: 19/02/2023
* Descripción: este script perform the NumPy´s Bakery.

1) ABRAN EL CUADERNO QUE CREARON DURANTE LA CLASE ANTERIOR: INTRODUCCIÓN A LOS ARRAYS DE NUMPY

2) Actualicen el quantity_sold_array para incluir la venta de 2 tartas, 3 bandejas de dulces, 16 magdalenas y 5 panes de plátano. También se darán cuenta que una de las galletas que pensaron que se había vendido en realidad se cayó al suelo, así que editen quantity_sold_array de 40 a 39.

3) Determinen la cantidad de dinero recaudado de la venta de cada elemento en la venta de la panadería.

4) Creen un array de NumPy "quantity_leftover" que incluya la cantidad de cada elemento restante al final de la venta: 2 pasteles, 1 tarta, 6 bandejas de dulces, 2 panes de plátano. Pista: Asegúrense de incluir “0” de cada elemento que se haya vendido. ¿Por qué esto es importante cuando se crea un array?

5) El club decide vender los elementos restantes a mitad de precio, y todo se venda rápidamente. Determinen cuanto dinero se recaudó de la venta de liquidación.

6) ¿Cuánto dinero total se recaudó de la venta de panadería (incluido la venta del precio total y los elementos liquidados)?

Pista: La respuesta final debería ser de $213.50, pero deben asegurarse de obtener esta respuesta con sus conocimientos de codificación de NumPy.

Question 1:

In [1]:
precio = [2, 1, 10]
type(precio)

list

In [2]:
cantidad_vendida = [17, 40, 1]
type(cantidad_vendida)

list

In [3]:
income = ['']
type(income)

list

In [4]:
import numpy as np

In [5]:
precio_array = np.array(precio)
cantidad_vendida_array = np.array(cantidad_vendida)
income_array = np.array(income)
type(precio_array)
type(cantidad_vendida_array)
type(income_array)

numpy.ndarray

In [6]:
income_array = precio_array * cantidad_vendida_array
print(income_array)

[34 40 10]


In [7]:
costo_array = np.array([0.25, 0.50, 5.00])

In [8]:
ganancia_array = precio_array - costo_array
print(ganancia_array)

[1.75 0.5  5.  ]


In [9]:
ganancia_array > 2.00

array([False, False,  True])

In [10]:
precio_array = precio_array + [7]
print(precio_array)

[ 9  8 17]


In [11]:
# Sólo fíjate el error
precio_array = precio_array - [7]
# La manera apropiada de adjuntar un elemento a un arreglo
precio_array = np.append(precio_array, 7)
print(precio_array)

[ 2  1 10  7]


In [12]:
precio_array = np.append(precio_array, [4.50, 3, 4, 9])
print(precio_array)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [13]:
print(precio_array.dtype)

float64


In [14]:
precio_array = np.delete(precio_array, -1)
print(precio_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


In [15]:
precio_array[2] = 12
print(precio_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


Questions 2-6:

In [16]:
cantidad_vendida_array = np.append(cantidad_vendida, [2, 3, 16, 5])
print(cantidad_vendida_array)

[17 40  1  2  3 16  5]


In [17]:
cantidad_vendida_array[1] = 39
print(cantidad_vendida_array)

[17 39  1  2  3 16  5]


In [19]:
income2 = ['']
type(income2)

list

In [20]:
income2_array = np.array(income2)
type(income2_array)

numpy.ndarray

In [22]:
income2_array = precio_array * cantidad_vendida_array
print(income2_array)

[34.  39.  12.  14.  13.5 48.  20. ]


In [23]:
cantidad_restante = [0, 0, 2, 1, 6, 0, 2]
type(cantidad_restante)

list

In [24]:
precio_variante = [2, 1, 6, 3.5, 2.25, 3, 2]
type(precio_variante)

list

In [26]:
income3 = ['']
type(income3)

list

In [27]:
cantidad_restante_array = np.array(cantidad_restante)
type(cantidad_restante_array)
precio_variante_array = np.array(precio_variante)
type(precio_variante_array)
income3_array = np.array(income3)
type(income3_array)

numpy.ndarray

In [28]:
income3_array = precio_variante_array * cantidad_restante_array
print(income3_array)

[ 0.   0.  12.   3.5 13.5  0.   4. ]


In [29]:
revenues = np.sum([income2_array, income3_array])
print(revenues)

213.5
